apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        imagePullPolicy: Never
        image: ftps_image:latest
        ports:
        -   name: ftps
            containerPort: 21
        -   name: ftps-send
            containerPort: 21100
        livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "pgrep vsftpd && pgrep telegraf"
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: ftps
spec:
    type: LoadBalancer
    selector:
        app: ftps
    ports:
        -   targetPort: 21
            port: 21
            name: ftps
        -   targetPort: 21100
            port: 21100
            name: ftps-send