apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      restartPolicy: Always
      containers:
      - name: grafana
        imagePullPolicy: Never
        image: grafana_image:latest
        ports:
        -   name: grafana
            containerPort: 3000
        livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "pgrep grafana-server && pgrep telegraf"
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: grafana
spec:
    type: LoadBalancer
    selector:
        app: grafana
    ports:
        -   port: 3000
            targetPort: 3000
            name: grafana