apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        imagePullPolicy: Never
        image: nginx_image:latest
        ports:
        -   name: nginx
            containerPort: 80
        -   name: nginx-ssl
            containerPort: 443
        -   name: nginx-ssh
            containerPort: 22
        livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "pgrep nginx && pgrep telegraf && pgrep sshd"
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: nginx
spec:
    type: LoadBalancer
    selector:
        app: nginx
    ports:
        -   targetPort: 80
            port: 80
            name: nginx
        -   targetPort: 443
            port: 443
            name: nginx-ssl
        -   targetPort: 22
            port: 600
            name: nginx-ssh