apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
      - name: phpmyadmin
        imagePullPolicy: Never
        image: phpmyadmin_image:latest
        ports:
        -   name: phpmyadmin
            containerPort: 5000
        livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "pgrep nginx && pgrep telegraf && pgrep php-fpm7"
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: phpmyadmin
spec:
    type: LoadBalancer
    selector:
        app: phpmyadmin
    ports:
        -   targetPort: 5000
            port: 5000
            name: phpmyadmin