apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
      - name: wordpress
        imagePullPolicy: Never
        image: wordpress_image:latest
        ports:
        -   name: wordpress
            containerPort: 5050
        livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "pgrep nginx && pgrep telegraf && pgrep php-fpm7"
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: wordpress
spec:
    type: LoadBalancer
    selector:
        app: wordpress
    ports:
        -   targetPort: 5050
            port: 5050
            name: wordpress